### PR TITLE
docs(tutorials): setup contribution guides and getting started guides

### PR DESCRIPTION
**Pull request by AntoineDao**
#4

### CODE REVIEW

**Review by theo-armour — APPROVED** [review]

**Comment by theo-armour** [comment]
looks interesting!

**Comment by AntoineDao** [comment]
Woah! Wait up! Can we apply a rule whereby the person making the PR has to also merge it? I added you as reviewer to get feedback and potentially discuss stuff. Also had a couple more changes I wanted to add to this PR. Does this sound ok going forward? 😄

**Comment by theo-armour** [comment]
@AntoineDao 

Of course!

**Comment by AntoineDao** [comment]
Also, it seems Travis is having a wobbly and they are accumulating a backlog of jobs so the documentation won't deploy for a little while I reckon. You can keep an eye on the CI job [here](https://travis-ci.org/ladybug-tools/spider-core/builds/514545676?utm_source=github_status&utm_medium=notification) and Travis' status [here](https://www.traviscistatus.com/#day)

**Comment by AntoineDao** [comment]
Urgh because I set up the node package deploy it has pushed everything to a specific folder which means docs are now found here: http://www.ladybug.tools/spider-core/@ladybug-tools/spider-core/0.0.0/ Will look into possibly fixing this.

**Comment by theo-armour** [comment]
looks like the docs moved on to here: https://www.ladybug.tools/spider-core/latest/

**Comment by AntoineDao** [comment]
Yes sorry I made another few changes I pushed straight to master yesterday as I wasn't happy with the super long URL. I reckon I'd might change on last time to HTTPS://ladybug.tools/spider-core/docs/latest

**Pull request merged**
